/**
 * ADR (Architecture Decision Record) schema and markdown renderer.
 */

import { z } from "zod"
import type { AdrContent } from "@/lib/ports/types"

export const AdrSchema = z.object({
  title: z.string().max(100),
  context: z.string().max(500),
  decision: z.string().max(1000),
  consequences: z.string().max(500),
  relatedEntities: z.array(z.string()).max(20),
  relatedFeatureAreas: z.array(z.string()).max(10),
})

export function renderAdrMarkdown(adr: AdrContent, prNumber: number): string {
  const date = new Date().toISOString().split("T")[0]

  return `# ADR: ${adr.title}

**Date:** ${date}
**Status:** Accepted
**Triggered by:** PR #${prNumber}

## Context

${adr.context}

## Decision

${adr.decision}

## Consequences

${adr.consequences}

## Related Entities

${adr.relatedEntities.map((e) => `- \`${e}\``).join("\n")}

## Related Feature Areas

${adr.relatedFeatureAreas.map((f) => `- ${f}`).join("\n")}

---

*This ADR was automatically generated by unerr based on significant changes detected during PR review.*
`
}

export function formatAdrFilename(title: string): string {
  const date = new Date().toISOString().split("T")[0]
  const slug = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 50)
  return `docs/adr/${date}-${slug}.md`
}
