/**
 * SCIP indexer for C and C++ via scip-clang.
 *
 * scip-clang is a Clang-based SCIP indexer from Sourcegraph that provides
 * precise cross-file code intelligence for C/C++ codebases. It requires
 * a compile_commands.json (generated by CMake, Bear, or similar tools).
 *
 * Falls back gracefully if scip-clang is not installed or the project
 * lacks a compilation database.
 */
import { execFile } from "node:child_process"
import { existsSync, unlinkSync } from "node:fs"
import { join } from "node:path"
import { promisify } from "node:util"

import { parseSCIPOutput } from "../../scip-decoder"
import type { ParsedEdge, ParsedEntity } from "../../types"
import type { SCIPOptions } from "../types"

const execFileAsync = promisify(execFile)

const SCIP_TIMEOUT_MS = 10 * 60 * 1000

export interface SCIPClangResult {
  entities: ParsedEntity[]
  edges: ParsedEdge[]
  coveredFiles: string[]
}

/**
 * Run scip-clang on a workspace root and parse the output.
 * Requires compile_commands.json in the workspace root.
 */
export async function runSCIPClang(
  opts: SCIPOptions,
  workspaceRoot: string,
  language: "c" | "cpp",
): Promise<SCIPClangResult> {
  const absRoot = join(opts.indexDir, workspaceRoot === "." ? "" : workspaceRoot)
  const outputFile = join(absRoot, "index.scip")

  try {
    if (!existsSync(join(absRoot, "compile_commands.json"))) {
      return { entities: [], edges: [], coveredFiles: [] }
    }

    await execFileAsync("scip-clang", ["--compdb-path", join(absRoot, "compile_commands.json"), "--index-output-path", outputFile], {
      cwd: absRoot,
      timeout: SCIP_TIMEOUT_MS,
      maxBuffer: 100 * 1024 * 1024,
    })

    if (!existsSync(outputFile)) {
      return { entities: [], edges: [], coveredFiles: [] }
    }

    const result = parseSCIPOutput(outputFile, opts.repoId, language, opts.isIncluded)

    try {
      unlinkSync(outputFile)
    } catch {
      // ignore cleanup errors
    }

    return result
  } catch (error: unknown) {
    const message = error instanceof Error ? error.message : String(error)
    console.warn(`[scip-clang] Failed for ${absRoot}: ${message}`)
    return { entities: [], edges: [], coveredFiles: [] }
  }
}
