/**
 * Auto-PR onboarding — creates a GitHub PR with Bootstrap Rule + MCP config.
 * Triggered after first successful indexing (status → "ready" AND onboardingPrUrl IS NULL).
 */

import type { Container } from "@/lib/di/container"
import { generateApiKey } from "@/lib/mcp/auth"
import type { RepoRecord } from "@/lib/ports/relational-store"
import { generateBootstrapRule } from "./bootstrap-rule"

const MCP_SERVER_URL = process.env.MCP_SERVER_URL ?? "https://mcp.unerr.dev"

interface AutoPrResult {
  prUrl: string
  prNumber: number
  branch: string
  apiKeyPrefix: string
}

/**
 * Generate .cursor/mcp.json content for MCP server configuration.
 */
export function generateMcpConfig(apiKey: string): string {
  return JSON.stringify(
    {
      mcpServers: {
        unerr: {
          url: `${MCP_SERVER_URL}/mcp`,
          transport: "streamable-http",
          headers: {
            Authorization: `Bearer ${apiKey}`,
          },
        },
      },
    },
    null,
    2
  )
}

/**
 * Generate the PR body with setup instructions.
 */
function generatePrBody(repoName: string): string {
  return `## unerr Code Intelligence

This PR adds unerr integration to your repository:

- **Bootstrap Rule** (\`.cursor/rules/unerr.mdc\`) — Instructs your AI coding agent to sync context with unerr's knowledge graph before and after code generation
- **MCP Configuration** (\`.cursor/mcp.json\`) — Connects your IDE to unerr's hosted MCP server

### What this enables

Once merged, any team member using Cursor (or any MCP-compatible IDE) will automatically get:

- **\`search_code\`** — Semantic search across your codebase
- **\`get_function\`** — Deep function details with callers and callees
- **\`get_class\`** — Class details with inheritance chain
- **\`get_file\`** — File overview with all entities
- **\`get_callers\` / \`get_callees\`** — Call graph traversal
- **\`get_imports\`** — Import chain analysis
- **\`get_project_stats\`** — Repository statistics
- **\`sync_local_diff\`** — Sync uncommitted changes to the cloud graph

### Getting started

1. **Merge this PR**
2. Open the repository in Cursor
3. Your AI agent will automatically use unerr's knowledge graph

### For Claude Code users

Run this command instead of using the \`.cursor/mcp.json\` file:

\`\`\`bash
claude mcp add unerr --transport streamable-http --url ${MCP_SERVER_URL}/mcp --header "Authorization: Bearer <your-api-key>"
\`\`\`

You can generate an API key at: \`Settings → ${repoName} → Connect to IDE\`

---

*Automatically generated by [unerr](https://unerr.dev)*`
}

/**
 * Create the onboarding PR for a repository.
 * Creates an API key, generates config files, and opens a GitHub PR.
 */
export async function createOnboardingPr(
  repo: RepoRecord,
  installationToken: string,
  container: Container
): Promise<AutoPrResult> {
  // Generate a dedicated API key for this repo's MCP config
  const { raw: apiKeyRaw, hash: apiKeyHash, prefix: apiKeyPrefix } = generateApiKey()

  await container.relationalStore.createApiKey({
    organizationId: repo.organizationId,
    repoId: repo.id,
    name: "Auto-generated (onboarding PR)",
    keyPrefix: apiKeyPrefix,
    keyHash: apiKeyHash,
    scopes: ["mcp:read", "mcp:sync"],
  })

  // Generate file contents
  const bootstrapRule = generateBootstrapRule(repo.fullName)
  const mcpConfig = generateMcpConfig(apiKeyRaw)

  // Parse owner/repo from fullName
  const [owner, repoName] = repo.fullName.split("/")
  if (!owner || !repoName) {
    throw new Error(`Invalid repo fullName: ${repo.fullName}`)
  }

  const branchName = `unerr/onboarding-${repo.id.slice(0, 8)}`

  // Use GitHub API via git host to create PR
  const pr = await container.gitHost.createPullRequest(owner, repoName, {
    title: "Enable unerr Code Intelligence for your AI agents",
    body: generatePrBody(repo.fullName),
    head: branchName,
    base: repo.defaultBranch ?? "main",
    token: installationToken,
    files: [
      { path: ".cursor/rules/unerr.mdc", content: bootstrapRule },
      { path: ".cursor/mcp.json", content: mcpConfig },
    ],
  })

  // Store PR info in repo record
  await container.relationalStore.updateRepoOnboardingPr(
    repo.id,
    `https://github.com/${repo.fullName}/pull/${pr.number}`,
    pr.number
  )

  return {
    prUrl: `https://github.com/${repo.fullName}/pull/${pr.number}`,
    prNumber: pr.number,
    branch: branchName,
    apiKeyPrefix,
  }
}
