/**
 * Context document generator — compiles the indexing pipeline's output into
 * a concise, actionable UNERR_CONTEXT.md markdown artifact.
 *
 * Design goals:
 *  1. Scannable in 30 seconds (executive summary first)
 *  2. Every problem has specific entity names and file locations
 *  3. Target ~150 lines for a medium codebase, never over 300
 *  4. Show insights invisible without graph analysis
 */

import type { IGraphStore } from "@/lib/ports/graph-store"
import type {
  ADRDoc,
  DomainOntologyDoc,
  EntityDoc,
  FeatureAggregation,
  HealthReportDoc,
  PatternDoc,
  ProjectStats,
  RuleDoc,
} from "@/lib/ports/types"

// ── Constants ────────────────────────────────────────────────────────────────

const NOISE_FEATURE_PATTERN =
  /^(foo|bar|baz|test_|example_|stub|placeholder|sample_|fixture|abstract_test|omit_deep|type_tagged)/i

const PROGRAMMING_NOISE_TERMS = new Set([
  "type", "function", "class", "string", "object", "array", "boolean",
  "number", "null", "void", "key", "value", "index", "param", "arg",
  "var", "let", "const", "return", "import", "export", "module", "interface",
  "enum", "generic", "promise", "async", "await", "callback", "error",
  "undefined", "any", "never", "unknown", "true", "false",
])

const SEVERITY_ORDER: Record<string, number> = { high: 0, medium: 1, low: 2 }

// ── Helpers ──────────────────────────────────────────────────────────────────

function computeGrade(risks: HealthReportDoc["risks"]): string {
  const high = risks.filter((r) => r.severity === "high").length
  const med = risks.filter((r) => r.severity === "medium").length
  if (high >= 3) return "F"
  if (high >= 1) return "D"
  if (med > 3) return "C"
  if (med > 0) return "B"
  return "A"
}

function resolveEntity(
  entityMap: Map<string, EntityDoc>,
  id: string,
  name?: string,
  filePath?: string,
): string {
  const ent = entityMap.get(id)
  const n = ent?.name ?? name ?? id
  const fp = ent?.file_path ?? filePath
  const line = ent?.start_line as number | undefined
  if (fp && line) return `\`${n}\` (${fp}:${line})`
  if (fp) return `\`${n}\` (${fp})`
  return `\`${n}\``
}

function truncate(text: string, max: number): string {
  if (text.length <= max) return text
  return text.slice(0, max - 3).trimEnd() + "..."
}

function pct(n: number, total: number): string {
  if (total === 0) return "0%"
  return Math.round((n / total) * 100) + "%"
}

function severityLabel(s: string): string {
  if (s === "high") return "Critical"
  if (s === "medium") return "Warning"
  return "Info"
}

// ── Section builders ─────────────────────────────────────────────────────────

function buildHeader(
  projectName: string,
  date: string,
  grade: string | null,
  stats: ProjectStats | null,
  confidence: number | null,
): string[] {
  const parts = [`# ${projectName} — Code Intelligence Report`]
  const meta: string[] = [`Auto-generated by [unerr](https://unerr.dev) on ${date}`]
  if (grade) meta.push(`Grade: ${grade}`)
  if (stats) {
    const total = stats.functions + stats.classes + stats.interfaces + stats.variables
    meta.push(`${total.toLocaleString()} entities`)
    meta.push(`${stats.files.toLocaleString()} files`)
  }
  if (confidence !== null) meta.push(`${Math.round(confidence * 100)}% avg confidence`)
  parts.push(`> ${meta.join(" | ")}`)
  parts.push("")
  return parts
}

function buildProjectOverview(ontology: DomainOntologyDoc | null): string[] {
  if (!ontology) return []
  const has =
    ontology.project_description || (ontology.tech_stack && ontology.tech_stack.length > 0) || ontology.project_domain
  if (!has) return []

  const out: string[] = ["## Project Overview", ""]
  if (ontology.project_description) {
    out.push(ontology.project_description, "")
  }
  if (ontology.tech_stack && ontology.tech_stack.length > 0) {
    out.push(`**Tech Stack:** ${ontology.tech_stack.join(", ")}`)
  }
  if (ontology.project_domain) {
    out.push(`**Domain:** ${ontology.project_domain}`)
  }
  out.push("")
  return out
}

function buildExecutiveSummary(
  healthReport: HealthReportDoc | null,
  entityMap: Map<string, EntityDoc>,
  featureCount: number,
  ruleCount: number,
  patternCount: number,
): string[] {
  if (!healthReport || healthReport.risks.length === 0) return []

  const highCount = healthReport.risks.filter((r) => r.severity === "high").length
  const medCount = healthReport.risks.filter((r) => r.severity === "medium").length

  const out: string[] = ["## Executive Summary", ""]

  const issueParts: string[] = []
  if (highCount > 0) issueParts.push(`${highCount} critical`)
  if (medCount > 0) issueParts.push(`${medCount} warning${medCount > 1 ? "s" : ""}`)
  out.push(`${issueParts.join(" and ")} detected.`)
  out.push("")

  // Top 3 risks, highest severity first
  const sorted = [...healthReport.risks].sort(
    (a, b) => (SEVERITY_ORDER[a.severity] ?? 2) - (SEVERITY_ORDER[b.severity] ?? 2),
  )

  for (const risk of sorted.slice(0, 3)) {
    out.push(`- **${risk.description}**`)
    if (risk.entities && risk.entities.length > 0) {
      const examples = risk.entities.slice(0, 3).map((e) => {
        if (e.detail) return `${resolveEntity(entityMap, e.id, e.name, e.filePath)} — ${e.detail}`
        return resolveEntity(entityMap, e.id, e.name, e.filePath)
      })
      const remaining = (risk.affectedCount ?? risk.entities.length) - 3
      const suffix = remaining > 0 ? `, and ${remaining} more` : ""
      out.push(`  ${examples.join(", ")}${suffix}`)
    }
  }

  out.push("")
  const summaryParts: string[] = []
  if (featureCount > 0) summaryParts.push(`${featureCount} business features`)
  if (ruleCount > 0) summaryParts.push(`${ruleCount} active rules`)
  if (patternCount > 0) summaryParts.push(`${patternCount} confirmed patterns`)
  if (summaryParts.length > 0) out.push(summaryParts.join(" | ") + ".")
  out.push("")
  return out
}

function buildAgentInsights(
  healthReport: HealthReportDoc | null,
  entityMap: Map<string, EntityDoc>,
): string[] {
  if (!healthReport) return []

  const out: string[] = []
  const risksByType = new Map<string, HealthReportDoc["risks"][0]>()
  for (const r of healthReport.risks) {
    if (r.riskType) risksByType.set(r.riskType, r)
  }

  const hubRisk = risksByType.get("high_fan_in")
  const godRisk = risksByType.get("high_fan_out")
  const cycleRisk = risksByType.get("circular_dependency")
  const taxonomyBreakdown = healthReport.taxonomy_breakdown
  const total = Object.values(taxonomyBreakdown).reduce((s, n) => s + n, 0)
  const utilityRatio = total > 0 ? (taxonomyBreakdown["UTILITY"] ?? 0) / total : 0

  const hasContent = hubRisk || godRisk || cycleRisk || utilityRatio > 0.8
  if (!hasContent) return []

  out.push("## What Your AI Agent Can't See", "")
  out.push("*Insights derived from graph analysis, git history, and dependency structure — invisible to text-based tools.*")
  out.push("")

  if (hubRisk?.entities && hubRisk.entities.length > 0) {
    out.push("### Hub Functions (High Blast Radius)")
    out.push("These functions are called by 10+ others. Changes here cascade widely.")
    out.push("")
    for (const e of hubRisk.entities.slice(0, 5)) {
      out.push(`- ${resolveEntity(entityMap, e.id, e.name, e.filePath)}${e.detail ? ` — ${e.detail}` : ""}`)
    }
    out.push("")
  }

  if (godRisk?.entities && godRisk.entities.length > 0) {
    out.push("### God Functions (Excessive Responsibility)")
    out.push("These functions call 10+ others. Consider decomposing.")
    out.push("")
    for (const e of godRisk.entities.slice(0, 5)) {
      out.push(`- ${resolveEntity(entityMap, e.id, e.name, e.filePath)}${e.detail ? ` — ${e.detail}` : ""}`)
    }
    out.push("")
  }

  if (cycleRisk?.entities && cycleRisk.entities.length > 0) {
    out.push("### Circular Dependencies")
    for (const e of cycleRisk.entities.slice(0, 5)) {
      out.push(`- ${e.detail ?? e.name}`)
    }
    out.push("")
  }

  if (utilityRatio > 0.8) {
    const utilPct = Math.round(utilityRatio * 100)
    out.push("### Taxonomy Signal")
    out.push(
      `${utilPct}% of entities classified as UTILITY. This typically means entity names are too generic ` +
      `for the LLM to infer business purpose, or the codebase lacks clear domain boundaries. ` +
      `Adding docstrings to key business functions improves classification accuracy.`,
    )
    out.push("")
  }

  return out
}

function buildHealthTable(
  healthReport: HealthReportDoc | null,
  entityMap: Map<string, EntityDoc>,
): string[] {
  if (!healthReport || healthReport.risks.length === 0) return []

  const out: string[] = ["## Architecture Health", ""]

  // Summary table — one row per category, highest severity wins
  const byCategory = new Map<string, { description: string; severity: string; affectedCount: number }>()
  for (const risk of healthReport.risks) {
    const cat = risk.category ?? "other"
    const existing = byCategory.get(cat)
    if (!existing || (SEVERITY_ORDER[risk.severity] ?? 2) < (SEVERITY_ORDER[existing.severity] ?? 2)) {
      byCategory.set(cat, {
        description: risk.description,
        severity: risk.severity,
        affectedCount: risk.affectedCount ?? 0,
      })
    }
  }

  const categoryRows = [...byCategory.entries()].sort(
    (a, b) => (SEVERITY_ORDER[a[1].severity] ?? 2) - (SEVERITY_ORDER[b[1].severity] ?? 2),
  )

  out.push("| Category | Finding | Severity |")
  out.push("|----------|---------|----------|")
  for (const [cat, info] of categoryRows) {
    const label = cat.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase())
    out.push(`| ${label} | ${info.description} | ${severityLabel(info.severity)} |`)
  }
  out.push("")

  // Detail blocks for high-severity risks only
  const highRisks = healthReport.risks.filter(
    (r) => r.severity === "high" && r.entities && r.entities.length > 0,
  )

  if (highRisks.length > 0) {
    for (const risk of highRisks) {
      const label = (risk.category ?? risk.riskType ?? "issue").replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase())
      out.push(`**${label}** (top ${Math.min(risk.entities!.length, 5)}):`)
      for (const e of risk.entities!.slice(0, 5)) {
        if (e.detail) {
          out.push(`- ${resolveEntity(entityMap, e.id, e.name, e.filePath)} — ${e.detail}`)
        } else {
          out.push(`- ${resolveEntity(entityMap, e.id, e.name, e.filePath)}`)
        }
      }
      out.push("")
    }
  }

  return out
}

function buildCodebaseAnatomy(
  stats: ProjectStats | null,
  taxonomyBreakdown: Record<string, number> | null,
): string[] {
  if (!stats) return []

  const out: string[] = ["## Codebase Anatomy", ""]

  // Entity counts — single line
  const parts = [
    `${stats.files.toLocaleString()} files`,
    `${stats.functions.toLocaleString()} functions`,
    `${stats.classes.toLocaleString()} classes`,
    `${stats.interfaces.toLocaleString()} interfaces`,
    `${stats.variables.toLocaleString()} variables`,
  ]
  out.push(parts.join(" | "))

  // Languages — single line
  if (stats.languages && Object.keys(stats.languages).length > 0) {
    const sorted = Object.entries(stats.languages).sort((a, b) => b[1] - a[1]).slice(0, 5)
    const langParts = sorted.map(([lang, count]) => `${lang} (${count})`)
    out.push(`**Languages:** ${langParts.join(", ")}`)
  }

  // Taxonomy — single line
  if (taxonomyBreakdown) {
    const total = Object.values(taxonomyBreakdown).reduce((s, n) => s + n, 0)
    if (total > 0) {
      const taxParts = Object.entries(taxonomyBreakdown)
        .sort((a, b) => b[1] - a[1])
        .map(([tax, count]) => `${count.toLocaleString()} ${tax} (${pct(count, total)})`)
      out.push(`**Taxonomy:** ${taxParts.join(", ")}`)
    }
  }

  out.push("")
  return out
}

function buildFeatureMap(
  features: FeatureAggregation[],
  entityMap: Map<string, EntityDoc>,
): string[] {
  if (features.length === 0) return []

  // Filter noise
  const significant = features.filter(
    (f) => f.entity_count > 2 && !NOISE_FEATURE_PATTERN.test(f.feature_tag),
  )

  // Partition by taxonomy
  const business: FeatureAggregation[] = []
  const infrastructure: FeatureAggregation[] = []
  const utilities: FeatureAggregation[] = []

  for (const f of significant) {
    const vertCount = f.taxonomy_breakdown["VERTICAL"] ?? 0
    const horizCount = f.taxonomy_breakdown["HORIZONTAL"] ?? 0
    if (vertCount > 0) business.push(f)
    else if (horizCount > 0) infrastructure.push(f)
    else utilities.push(f)
  }

  business.sort((a, b) => b.entity_count - a.entity_count)
  infrastructure.sort((a, b) => b.entity_count - a.entity_count)

  const filteredOut = features.length - significant.length
  const utilityEntityTotal = utilities.reduce((s, f) => s + f.entity_count, 0)

  // Nothing meaningful to show
  if (business.length === 0 && infrastructure.length === 0 && utilities.length === 0) return []

  const out: string[] = ["## Feature Map", ""]

  const renderFeature = (f: FeatureAggregation) => {
    const taxParts = Object.entries(f.taxonomy_breakdown)
      .filter(([, c]) => c > 0)
      .map(([t, c]) => `${c} ${t}`)
      .join(", ")
    const conf = Math.round(f.average_confidence * 100)
    const tag = f.feature_tag.replace(/_/g, " ").replace(/\b\w/g, (c) => c.toUpperCase())

    out.push(`**${tag}** — ${f.entity_count} entities (${taxParts}) | ${conf}% confidence`)

    // Resolve entry points
    if (f.entry_points.length > 0) {
      const resolved = f.entry_points.slice(0, 3).map((id) => resolveEntity(entityMap, id))
      out.push(`Entry: ${resolved.join(", ")}`)
    }
    out.push("")
  }

  if (business.length > 0) {
    out.push("### Business Features", "")
    for (const f of business.slice(0, 10)) renderFeature(f)
  }

  if (infrastructure.length > 0) {
    out.push("### Shared Infrastructure", "")
    for (const f of infrastructure.slice(0, 5)) renderFeature(f)
  }

  // Collapsed utility summary
  if (utilities.length > 0) {
    out.push(`*Plus ${utilities.length} utility groups (${utilityEntityTotal.toLocaleString()} entities total)*`)
    out.push("")
  }
  if (filteredOut > 0) {
    out.push(`*${filteredOut} minor groups filtered (single-entity or test fixtures)*`)
    out.push("")
  }

  return out
}

function buildConventions(rules: RuleDoc[], patterns: PatternDoc[]): string[] {
  if (rules.length === 0 && patterns.length === 0) return []

  const out: string[] = ["## Team Conventions", ""]

  if (rules.length > 0) {
    out.push("### Architecture Rules", "")
    for (const rule of rules) {
      const badge =
        rule.enforcement === "block" ? "[MUST]" : rule.enforcement === "warn" ? "[SHOULD]" : "[MAY]"
      out.push(`- ${badge} **${rule.title}**: ${rule.description}`)
    }
    out.push("")
  }

  if (patterns.length > 0) {
    out.push("### Detected Patterns", "")
    for (const pattern of patterns.slice(0, 15)) {
      const rate = Math.round(pattern.adherenceRate * 100)
      out.push(`- **${pattern.title}** (${rate}% adherence, ${pattern.type})`)
    }
    out.push("")
  }

  return out
}

function buildADRs(adrs: ADRDoc[]): string[] {
  if (adrs.length === 0) return []

  const out: string[] = ["## Architecture Decisions", ""]

  for (const adr of adrs.slice(0, 5)) {
    const tag = adr.feature_area ? ` \`${adr.feature_area}\`` : ""
    out.push(`**${adr.title}**${tag}`)
    out.push(`Context: ${truncate(adr.context, 200)}`)
    out.push(`Decision: ${truncate(adr.decision, 250)}`)
    if (adr.consequences) {
      out.push(`Trade-offs: ${truncate(adr.consequences, 200)}`)
    }
    out.push("")
  }

  return out
}

function buildDomainVocabulary(ontology: DomainOntologyDoc | null): string[] {
  if (!ontology) return []

  // Determine which terms are domain-relevant
  const domainTermSet = ontology.term_tiers?.domain
    ? new Set(ontology.term_tiers.domain.map((t) => t.toLowerCase()))
    : null

  const sorted = [...ontology.terms].sort((a, b) => b.frequency - a.frequency)

  const filtered = sorted.filter((t) => {
    const lower = t.term.toLowerCase()
    if (PROGRAMMING_NOISE_TERMS.has(lower)) return false
    if (domainTermSet) return domainTermSet.has(lower)
    return true
  })

  if (filtered.length === 0) return []

  const ubiq = ontology.ubiquitous_language ?? {}

  const out: string[] = ["## Domain Vocabulary", ""]
  out.push("| Term | Frequency | Definition |")
  out.push("|------|-----------|------------|")

  for (const term of filtered.slice(0, 20)) {
    const definition = ubiq[term.term] ?? ubiq[term.term.toLowerCase()] ?? ""
    out.push(`| ${term.term} | ${term.frequency} | ${definition || "—"} |`)
  }
  out.push("")

  return out
}

// ── Main ─────────────────────────────────────────────────────────────────────

export async function generateContextDocument(
  orgId: string,
  repoId: string,
  graphStore: IGraphStore,
): Promise<string> {
  const [projectStats, healthReport, features, ontology, adrs, patterns, rules, allEntities] =
    await Promise.all([
      graphStore.getProjectStats(orgId, repoId).catch(() => null),
      graphStore.getHealthReport(orgId, repoId).catch((): HealthReportDoc | null => null),
      graphStore.getFeatureAggregations(orgId, repoId).catch((): FeatureAggregation[] => []),
      graphStore.getDomainOntology(orgId, repoId).catch((): DomainOntologyDoc | null => null),
      graphStore.getADRs(orgId, repoId).catch((): ADRDoc[] => []),
      graphStore.queryPatterns(orgId, { orgId, repoId, status: "confirmed", limit: 50 }).catch((): PatternDoc[] => []),
      graphStore.queryRules(orgId, { orgId, repoId, status: "active", limit: 50 }).catch((): RuleDoc[] => []),
      graphStore.getAllEntities(orgId, repoId).catch((): EntityDoc[] => []),
    ])

  // Build entity lookup map for O(1) resolution
  const entityMap = new Map<string, EntityDoc>()
  for (const e of allEntities) {
    entityMap.set(e.id, e)
  }

  const projectName = ontology?.project_name ?? "Project"
  const date = new Date().toISOString().split("T")[0]!
  const grade = healthReport ? computeGrade(healthReport.risks) : null

  // Count significant features (for summary line)
  const significantFeatures = features.filter(
    (f) => f.entity_count > 2 && !NOISE_FEATURE_PATTERN.test(f.feature_tag),
  )

  const sections = [
    buildHeader(projectName, date, grade, projectStats, healthReport?.average_confidence ?? null),
    buildProjectOverview(ontology),
    buildExecutiveSummary(healthReport, entityMap, significantFeatures.length, rules.length, patterns.length),
    buildAgentInsights(healthReport, entityMap),
    buildHealthTable(healthReport, entityMap),
    buildCodebaseAnatomy(projectStats, healthReport?.taxonomy_breakdown ?? null),
    buildFeatureMap(features, entityMap),
    buildConventions(rules, patterns),
    buildADRs(adrs),
    buildDomainVocabulary(ontology),
  ]

  const lines = sections.flat()

  // Footer
  lines.push("---")
  lines.push("")
  lines.push("*Generated by [unerr](https://unerr.dev) — Code Intelligence Platform*")

  return lines.join("\n")
}
